name: ci-build

on:
  push:
    branches: [ main, feature/cicd ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Print
        run: | 
          echo "${env:GITHUB_RUN_ID}"
      #- uses: actions/checkout@v2
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 6.0.x
      #- name: Restore dependencies
      #  run: dotnet restore
      #- name: Build
      #  run: dotnet build --no-restore
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pack
      run: |
        env
        #dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID CryptoNetLib/CryptoNetLib.csproj
    - name: Print versin
      run: echo ""