name: .NET

on:
  push:
    branches: [ main, feature/cicd ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      VERSION: ${env:GITHUB_RUN_ID}
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.x
    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: |
        env
        #echo ${{ env:VERSION }}
        echo ${{ env.VERSION }}
        #dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID CryptoNetLib/CryptoNetLib.csproj
    - name: Print versin
      run: |
        echo "${env:GITHUB_RUN_ID}"
        echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        echo "Version="${VERSION}
